finario:
  subdomain: finarioapp
  use_ssl: false
  login: finariobot
  password: welcome1
  room: Chat Room

sunmath:
  subdomain: flipstone
  use_ssl: false
  login: flipstone
  password: welcome1
  room: Sunmath
